Adapt MSVC wrapper to changes in CMake

diff --git a/toolchains/msvcrun b/toolchains/msvcrun
--- a/toolchains/msvcrun
+++ b/toolchains/msvcrun
@@ -83,7 +83,10 @@ done
 vcvars="C:\\vcvars-${msvcver}-${msvcarch}.bat"
 [ ! -f "$(winepath -u "$vcvars")" ] && vcvars="C:\\vcvars-${msvcver}.bat"
 
-if [ "$exe" = 'cmd' ]
-	then exec wineconsole cmd /K call "$vcvars" \> nul \& prompt "\$p \$lMSVC-${msvcver}-${msvcarch}\$g " "${args[@]}"
-	else exec "$here/run.cpp" wine cmd /C call "$vcvars" \> nul \& "$exe" "${args[@]}"
-fi
+[ "$exe" = 'cmd' ] && exec wineconsole cmd /K call "$vcvars" \> nul \& prompt "\$p \$lMSVC-${msvcver}-${msvcarch}\$g " "${args[@]}"
+
+"$here/run.cpp" wine cmd /C call "$vcvars" \> nul \& "$exe" "${args[@]}"
+
+rc=$?
+[ "$exe" = 'mt' ] && [ $rc = 1 ] && rc=187 # = 0xbb, special case so CMake doesn't think mt failed when it returns 0x41020001 which is truncated to 0x01
+exit $rc
